### ISSUE TITLE
Possible copyright violation?

### ISSUE THREAD

**Issue by danmarsden** [safatshahin-dev/moodle-block_simple_calculator#1]
your Calculator Javascript class looks extremely like a number of example JS code that is floating around - did you copy this from somewhere? - you need to track down the original class and find out what the original license was and put that detail into your header - you can't put this line in:
https://github.com/safatshahin-dev/moodle-block_simple_calculator/blob/master/assets/js/calculator.js#L21

Unless you are actually the original author of that class.

Once you've worked that out and confirmed that whatever licence it was originally published under is compatible with GPL (which your Moodle plugin must be) you will need to add a thirdpartylibs.xml file to your plugin describing that library - more detail on that is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml

This is a definite blocker for plugins db approval.

**Comment by safatshahin** [comment]
thanks for informing @danmarsden 
I would love to type stackoverflow.com as that's where all the js idea came from.
all the calculators using vanilla js shares the same method and code path, even before starting this plugin, with the initial research of using a calculator with vanilla js, I was pretty much going through the same type of codes which makes it quite difficult to identify the original author.
I have made the author unknown, for now, will give it another research for the original genius, will change if found.
