### ISSUE TITLE
incorrect location for css

### ISSUE THREAD

**Issue by danmarsden** [safatshahin-dev/moodle-block_simple_calculator#4]
Plugins should store their css within a styles.css file within the root of the plugin folder - this allows Moodle to cache the css correctly - if you store it in the styles.css file it will get picked up automatically and you don't need to include it manually in the page.

just make sure that anything you add to styles.css is really specific so that anything you add cannot clash with other areas of Moodle.

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:

.path-mod-assign .filething {
   color: red;
}
you also get extra specific tags around blocks etc.

note this is not a blocker for approval.

**Comment by safatshahin** [comment]
using sccs instead.

**Comment by danmarsden** [comment]
Looks like you mis-understood here.

here's an example of a block that stores the css correctly:
https://github.com/moodle/moodle/blob/master/blocks/course_list/styles.css

you may note that nothing in the blocks/course_list plugin needs to load that styles.css file - 

If you create a new "styles.css" file in the root of your plugin (like the course_list block)

and then copy the css rules from your calculator.css file into the new styles.css file

then delete this line completely:

https://github.com/safatshahin-dev/moodle-block_simple_calculator/blob/9f2c86db94f2ddce94923239313ef74e7e8f771d/classes/output/renderer.php#L31

Moodle will "auto-load" the css in your styles.css - (and compress/cache it) making the css perform even better.

Hopefully that makes sense... note this isn't a blocker for approval, but it improves the loading of your css a lot.

**Comment by safatshahin** [comment]
thanks for that, I am totally aware of that but I wanted the CSS to be independent as I always find with styles.css from different plugins conflicts with other plugins, anywho, added it like this and all my css are targeted to specifically named classes, so hope it never conflicts (this frustration came from some known community plugins which i already made pull req and they changed it after a long time), appreciate your explanation.
